import Header from '@/components/header';
import './globals.css';

export const metadata = {
	title: 'Yoma Care',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={' bg-primary-light'}>
				<Header />
				{children}
			</body>
		</html>
	);
}
